---
- name: Ensure config symbolic links are created
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ symlinks }}"

- name: Replace config items
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
  with_items: "{{ replacements }}"
